import React, {Fragment} from "react";

export const About = () => (
    <Fragment>
    <h1>About</h1>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis porro perspiciatis repellendus sed odit earum tempore maiores ullam numquam cupiditate laboriosam sit perferendis, beatae veritatis iusto nobis at totam voluptate exercitationem sint ab esse consequatur voluptatum nesciunt. Enim et eum cupiditate! Nobis omnis hic fugiat, rerum ut possimus deleniti. Quod iure illum vitae quae magnam quas veniam fuga, sed qui ducimus. Iusto pariatur recusandae nihil, exercitationem eius ut adipisci ratione eos nam vitae molestias, eum consequatur, rerum ipsa dolorem obcaecati deleniti architecto. Optio, accusamus voluptatibus? Nihil ea modi odit assumenda dolorum laborum quia sit et laudantium totam aut molestiae ipsum nulla laboriosam, adipisci commodi fuga unde similique quis quibusdam iure fugiat corporis voluptas facilis. Ipsum molestias impedit quaerat ullam officiis alias quas aperiam dolores repellat dolor itaque eligendi tenetur, hic earum voluptates quo. Molestias quisquam ex, iusto saepe alias quis fugit dolores! Delectus, deserunt hic soluta cupiditate in cum iure pariatur, perspiciatis eveniet nam totam impedit ea dolorum vero voluptatum, ab dolore quisquam fugiat eum dolorem? Nulla enim molestiae sequi? Distinctio ad in sed nemo beatae dolor velit illo sapiente quam facere aut fugiat, ut, iusto quia temporibus! Et obcaecati consequatur voluptate nam laudantium dignissimos aspernatur ducimus libero deserunt adipisci qui, maxime vero exercitationem illo est, quod commodi. Sit sed nostrum veniam vitae fugiat, debitis nam commodi nulla praesentium, explicabo in delectus cupiditate fuga aperiam? Nostrum, repellendus qui odio perspiciatis saepe earum tenetur doloremque quis, ipsum reiciendis recusandae dolorem eligendi at. Et, ab natus error quas ullam nam officia modi totam quod debitis aut ex, recusandae, ea id accusamus doloremque rem? Eligendi dolores magnam ipsa accusamus placeat sunt cum amet? Maxime officia similique doloribus laboriosam et, maiores ipsam, modi reiciendis odio, molestiae enim placeat aperiam? Deleniti earum et culpa dolores, illum suscipit. Eum accusantium amet, harum porro doloremque nam tempore?
    </p>
    <p>
       Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis porro perspiciatis repellendus sed odit earum tempore maiores ullam numquam cupiditate laboriosam sit perferendis, beatae veritatis iusto nobis at totam voluptate exercitationem sint ab esse consequatur voluptatum nesciunt. Enim et eum cupiditate! Nobis omnis hic fugiat, rerum ut possimus deleniti. Quod iure illum vitae quae magnam quas veniam fuga, sed qui ducimus. Iusto pariatur recusandae nihil, exercitationem eius ut adipisci ratione eos nam vitae molestias, eum consequatur, rerum ipsa dolorem obcaecati deleniti architecto. Optio, accusamus voluptatibus? Nihil ea modi odit assumenda dolorum laborum quia sit et laudantium totam aut molestiae ipsum nulla laboriosam, adipisci commodi fuga unde similique quis quibusdam iure fugiat corporis voluptas facilis. Ipsum molestias impedit quaerat ullam officiis alias quas aperiam dolores repellat dolor itaque eligendi tenetur, hic earum voluptates quo. Molestias quisquam ex, iusto saepe alias quis fugit dolores! 
    </p>
    </Fragment>
)